# Read the Docs configuration file

version: 2

build:
  os: ubuntu-22.04  # Use an OS version compatible with Python 3.11
  tools:
    python: "3.11"  # Use Python 3.11 for compatibility

sphinx:
  configuration: conf.py

python:
  install:
    - requirements: requirements.txt  # Ensure all dependencies are listed here
