# Read the Docs configuration file
version: 2

build:
  os: ubuntu-22.04  # Use an OS version that supports Python 3.11
  tools:
    python: "3.11"

sphinx:
  configuration: conf.py

python:
  install:
    - requirements: requirements.txt
