version: 2

build:
  os: ubuntu-22.04 
  tools:
    python: "3.11"

sphinx:
  configuration: conf.py

python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
    - pip_install: setuptools>=65.5.0
